name: Lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure Clean Jupyter Notebooks
        uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1

      - name: Setup Ruff
        uses: astral-sh/ruff-action@v3
        with:
          version: "0.12.4"
          args: "--version"

      - name: Run ruff check
        run: ruff check

      - name: Run ruff format
        run: ruff format --check

  type_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.8.14
        with:
          pixi-version: v0.50.2
          cache: true
          locked: true
          environments: ci

      - name: Run ty
        run: |
          pixi run -e ci ty check src/hepattn/models
          pixi run -e ci ty check src/hepattn/utils
          pixi run -e ci ty check src/hepattn/flex
          pixi run -e ci ty check tests/
