name: Lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure Clean Jupyter Notebooks
        uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1

      - name: Setup Ruff
        uses: astral-sh/ruff-action@v3
        with:
          version: "0.8.0"
          args: "--version"

      - name: Run ruff check
        run: ruff -v check --fix

      - name: Run ruff format
        run: ruff -v format

      #- name: Run pyright
      #  run: uv run pyright
